### ISSUE TITLE
Aun funciona este codigo?

### ISSUE THREAD

**Issue by Root-FTW** [dfrodriguez45/fortnite-store#1]
Entre a tu sobdominio de vercel donde tiene el proyecto pero solo me salen unos pocos cosméticos no actualizados.

Pleneas agregar el boton de "on-click" para que la gente lo pueda desplegar de forma facil en su vercel?

**Comment by dfrodriguez45** [comment]
@Root-FTW 
Si, si funciona pero no lo he actualizado aún, por ahora solo tiene la sección de Diario. Y con la actualización aun estoy trabajando en ello para no tener que recargar la página.

Con respecto a la última pregunta, te refieres a los detalles de los artículos o de las secciones?

**Comment by Root-FTW** [comment]
> @Root-FTW Si, si funciona pero no lo he actualizado aún, por ahora solo tiene la sección de Diario. Y con la actualización aun estoy trabajando en ello para no tener que recargar la página.
> 
> Con respecto a la última pregunta, te refieres a los detalles de los artículos o de las secciones?

Gracias por responder, estare atento a tu proyecto :D

Sobre que no salen los cosmeticos completos me refiero a que solo veo esto:

![image](https://user-images.githubusercontent.com/108767514/235254016-cb464ed6-5ecc-47c7-8331-ecdae7b72a15.png)

No veo el resto de la tienda, pero creo que es a lo que te refieres que vas ir actualizando :D

**Comment by dfrodriguez45** [comment]
@Root-FTW Gracias a ti ;D
Y sep, voy a ir actualizando para que se vea bien cuando salgan Bundles más que nada.
